In [ ]:
import pandas as pd

In [ ]:
from sklearn.datasets import load_diabetes

In [ ]:
data = load_diabetes()

In [ ]:
x = data.data
y = data.target

In [ ]:
df = pd.DataFrame(x, columns=data.feature_names)

In [ ]:
df

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [ ]:
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641

In [ ]:
df.tail()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [ ]:
df.info

<bound method DataFrame.info of           age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142
..        ...       ...       ...       ...       ...       ...       ...
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816

           s4        s5        s6
0   -0.002592  0.019907 -0.017646
1   -0.039493 -0.068332 -0.092204
2   -0.002592  0.002861 -0.025930
3    0.034309  0.022688 -0.009362
4   -0.002592 -0.031988 -0.046641
..        ...       ...       ...
437 -0.002592  0.031193  0.007207
438  0.034309 -0.018114  0.044485
439 -0.011080 -0.046883  0.015491
440  0.026560  0.044529 -0.025930
441 -0.039493 -0.004222  0.003064

[442 rows x 10 columns]>

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-null    float64
 6   s3      442 non-null    float64
 7   s4      442 non-null    float64
 8   s5      442 non-null    float64
 9   s6      442 non-null    float64
dtypes: float64(10)
memory usage: 34.7 KB

In [ ]:
df.describe()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
count,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02
mean,-2.511817e-19,1.230790e-17,-2.245564e-16,-4.797570e-17,-1.381499e-17,3.918434e-17,-5.777179e-18,-9.042540e-18,9.293722e-17,1.130318e-17
std,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02
min,-1.072256e-01,-4.464164e-02,-9.027530e-02,-1.123988e-01,-1.267807e-01,-1.156131e-01,-1.023071e-01,-7.639450e-02,-1.260971e-01,-1.377672e-01
25%,-3.729927e-02,-4.464164e-02,-3.422907e-02,-3.665608e-02,-3.424784e-02,-3.035840e-02,-3.511716e-02,-3.949338e-02,-3.324559e-02,-3.317903e-02
50%,5.383060e-03,-4.464164e-02,-7.283766e-03,-5.670422e-03,-4.320866e-03,-3.819065e-03,-6.584468e-03,-2.592262e-03,-1.947171e-03,-1.077698e-03
75%,3.807591e-02,5.068012e-02,3.124802e-02,3.564379e-02,2.835801e-02,2.984439e-02,2.931150e-02,3.430886e-02,3.243232e-02,2.791705e-02
max,1.107267e-01,5.068012e-02,1.705552e-01,1.320436e-01,1.539137e-01,1.987880e-01,1.811791e-01,1.852344e-01,1.335973e-01,1.356118e-01

In [ ]:
df["target"]=y

In [ ]:
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

In [ ]:
df.to_csv("diabetes.csv",index=False)

In [ ]:
df_diabetes=pd.read_csv("diabetes.csv")

In [ ]:
df_diabetes.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

In [ ]:
df_diabetes.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
437    False
438    False
439    False
440    False
441    False
Length: 442, dtype: bool

In [ ]:
df_diabetes[df_diabetes.duplicated()]

Empty DataFrame
Columns: [age, sex, bmi, bp, s1, s2, s3, s4, s5, s6, target]
Index: []

In [ ]:
df_diabetes.duplicated().sum()

0

In [ ]:
df_diabetes.isnull()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
437,False,False,False,False,False,False,False,False,False,False,False
438,False,False,False,False,False,False,False,False,False,False,False
439,False,False,False,False,False,False,False,False,False,False,False
440,False,False,False,False,False,False,False,False,False,False,False
441,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df_diabetes.isnull().any()

age       False
sex       False
bmi       False
bp        False
s1        False
s2        False
s3        False
s4        False
s5        False
s6        False
target    False
dtype: bool

In [ ]:
df_diabetes.isnull().any().any()

False

In [ ]:
df_diabetes.isnull().sum()

age       0
sex       0
bmi       0
bp        0
s1        0
s2        0
s3        0
s4        0
s5        0
s6        0
target    0
dtype: int64

In [ ]:
df_diabetes.isnull().sum().sum()

0

In [ ]:
df_diabetes.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

In [ ]:
df_diabetes["sex"].unique()

array([ 0.05068012, -0.04464164])

In [ ]:
df_diabetes.groupby("sex").mean()

,age,bmi,bp,s1,s2,s3,s4,s5,s6,target
sex,,,,,,,,,,
-0.044642,-0.007756,-0.003936,-0.010759,-0.001575,-0.006368,0.016923,-0.014826,-0.006693,-0.009291,149.021277
0.050680,0.008805,0.004468,0.012214,0.001788,0.007229,-0.019212,0.016832,0.007598,0.010548,155.666667

In [ ]:
import numpy as np

In [ ]:
df_diabetes.groupby("sex").agg([np.mean,max,min])

<ipython-input-32-5ffb28bd9808>:1: FutureWarning: The provided callable <function mean at 0x7e0cdf987d90> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df_diabetes.groupby("sex").agg([np.mean,max,min])
<ipython-input-32-5ffb28bd9808>:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df_diabetes.groupby("sex").agg([np.mean,max,min])
<ipython-input-32-5ffb28bd9808>:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df_diabetes.groupby("sex").agg([np.mean,max,min])

                age                           bmi                      \
               mean       max       min      mean       max       min
sex
-0.044642 -0.007756  0.096197 -0.107226 -0.003936  0.160855 -0.084886
 0.050680  0.008805  0.110727 -0.103593  0.004468  0.170555 -0.090275

                 bp                            s1  ...        s4        s5  \
               mean       max       min      mean  ...       min      mean
sex                                                ...
-0.044642 -0.010759  0.132044 -0.112399 -0.001575  ... -0.076395 -0.006693
 0.050680  0.012214  0.107944 -0.084856  0.001788  ... -0.076395  0.007598

                                     s6                          target  \
                max       min      mean       max       min        mean
sex
-0.044642  0.133597 -0.104366 -0.009291  0.135612 -0.137767  149.021277
 0.050680  0.133597 -0.126097  0.010548  0.135612 -0.104630  155.666667


             max   min
sex
-0.044642  346.0  25.0
 0.050680  341.0  39.0

[2 rows x 30 columns]

In [ ]:
df_diabetes.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

In [ ]:
df_diabetes.reset_index()

,index,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0
...,...,...,...,...,...,...,...,...,...,...,...,...
437,437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207,178.0
438,438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485,104.0
439,439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491,132.0
440,440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930,220.0
441,441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064,57.0

In [ ]:
df2_copy=df_diabetes.copy()

In [ ]:
df2_copy.drop(["age","sex"],axis=1)

,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0
...,...,...,...,...,...,...,...,...,...
437,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207,178.0
438,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485,104.0
439,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491,132.0
440,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930,220.0
441,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064,57.0

In [ ]:
df2_copy.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

In [ ]:
df2_copy.drop(["age","sex"],axis=1,inplace= True)
df2_copy.head()

,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

In [ ]:
df2_copy.drop(columns=["bmi","target"])

           bp        s1        s2        s3        s4        s5        s6
0    0.021872 -0.044223 -0.034821 -0.043401 -0.002592  0.019907 -0.017646
1   -0.026328 -0.008449 -0.019163  0.074412 -0.039493 -0.068332 -0.092204
2   -0.005670 -0.045599 -0.034194 -0.032356 -0.002592  0.002861 -0.025930
3   -0.036656  0.012191  0.024991 -0.036038  0.034309  0.022688 -0.009362
4    0.021872  0.003935  0.015596  0.008142 -0.002592 -0.031988 -0.046641
..        ...       ...       ...       ...       ...       ...       ...
437  0.059744 -0.005697 -0.002566 -0.028674 -0.002592  0.031193  0.007207
438 -0.067642  0.049341  0.079165 -0.028674  0.034309 -0.018114  0.044485
439  0.017293 -0.037344 -0.013840 -0.024993 -0.011080 -0.046883  0.015491
440  0.001215  0.016318  0.015283 -0.028674  0.026560  0.044529 -0.025930
441 -0.081413  0.083740  0.027809  0.173816 -0.039493 -0.004222  0.003064

[442 rows x 7 columns]

In [ ]:
df_diabetes.sort_values("bp")

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
224,-0.027310,-0.044642,-0.066563,-0.112399,-0.049727,-0.041397,0.000779,-0.039493,-0.035816,-0.009362,77.0
41,-0.099961,-0.044642,-0.067641,-0.108956,-0.074494,-0.072712,0.015505,-0.039493,-0.049872,-0.009362,55.0
93,-0.049105,-0.044642,-0.064408,-0.102070,-0.002945,-0.015406,0.063367,-0.047243,-0.033246,-0.054925,96.0
84,0.001751,-0.044642,-0.039618,-0.100934,-0.029088,-0.030124,0.044958,-0.050195,-0.068332,-0.129483,65.0
171,-0.020045,-0.044642,-0.046085,-0.098627,-0.075870,-0.059873,-0.017629,-0.039493,-0.051404,-0.046641,74.0
...,...,...,...,...,...,...,...,...,...,...,...
375,0.045341,0.050680,-0.002973,0.107944,0.035582,0.022485,0.026550,-0.002592,0.028020,0.019633,217.0
350,-0.027310,0.050680,0.060618,0.107944,0.012191,-0.017598,-0.002903,-0.002592,0.070207,0.135612,243.0
408,0.063504,-0.044642,-0.050396,0.107944,0.031454,0.019354,-0.017629,0.023608,0.058038,0.040343,189.0
71,-0.001882,-0.044642,0.033673,0.125158,0.024574,0.026243,-0.010266,-0.002592,0.026717,0.061054,270.0
340,-0.016412,-0.044642,-0.013751,0.132044,-0.009825,-0.003819,0.019187,-0.039493,-0.035816,-0.030072,216.0

In [ ]:
df_diabetes.sort_values(["bp","bmi"],ascending=False)

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
340,-0.016412,-0.044642,-0.013751,0.132044,-0.009825,-0.003819,0.019187,-0.039493,-0.035816,-0.030072,216.0
71,-0.001882,-0.044642,0.033673,0.125158,0.024574,0.026243,-0.010266,-0.002592,0.026717,0.061054,270.0
350,-0.027310,0.050680,0.060618,0.107944,0.012191,-0.017598,-0.002903,-0.002592,0.070207,0.135612,243.0
375,0.045341,0.050680,-0.002973,0.107944,0.035582,0.022485,0.026550,-0.002592,0.028020,0.019633,217.0
408,0.063504,-0.044642,-0.050396,0.107944,0.031454,0.019354,-0.017629,0.023608,0.058038,0.040343,189.0
...,...,...,...,...,...,...,...,...,...,...,...
171,-0.020045,-0.044642,-0.046085,-0.098627,-0.075870,-0.059873,-0.017629,-0.039493,-0.051404,-0.046641,74.0
84,0.001751,-0.044642,-0.039618,-0.100934,-0.029088,-0.030124,0.044958,-0.050195,-0.068332,-0.129483,65.0
93,-0.049105,-0.044642,-0.064408,-0.102070,-0.002945,-0.015406,0.063367,-0.047243,-0.033246,-0.054925,96.0
41,-0.099961,-0.044642,-0.067641,-0.108956,-0.074494,-0.072712,0.015505,-0.039493,-0.049872,-0.009362,55.0
224,-0.027310,-0.044642,-0.066563,-0.112399,-0.049727,-0.041397,0.000779,-0.039493,-0.035816,-0.009362,77.0

In [ ]:
df_diabetes.replace(151.0,999)

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,999.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0
...,...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207,178.0
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485,104.0
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491,132.0
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930,220.0
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064,57.0

In [ ]:
df_diabetes.columns

Index(['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6',
       'target'],
      dtype='object')

slicing and indexing of pandas object

In [ ]:
data=pd.Series(["a","b","c"],index=[1,3,5])
data

1    a
3    b
5    c
dtype: object

In [ ]:
data[1]

'a'

In [ ]:
data[1:3]

3    b
5    c
dtype: object

In [ ]:
data.loc[1]

'a'

In [ ]:
data.loc[1:3]

1    a
3    b
dtype: object

In [ ]:
data.iloc[1]

'b'

In [ ]:
data.iloc[1:3]

3    b
5    c
dtype: object

In [ ]:
import pandas as pd

df2 = pd.DataFrame({'Col1': [44, 9, 70,65], 'Col2': [47, 83, 88,39],'Col3':[64,21,88,46],'Col4':[67,36,12,46],'Col5':[67,87,58,88]},index=['a','b','c','d'])  # Create a sample DataFrame
print(df2)

   Col1  Col2  Col3  Col4  Col5
a    44    47    64    67    67
b     9    83    21    36    87
c    70    88    88    12    58
d    65    39    46    46    88

In [ ]:
df2

   Col1  Col2  Col3  Col4  Col5
a    44    47    64    67    67
b     9    83    21    36    87
c    70    88    88    12    58
d    65    39    46    46    88

In [ ]:
df2["Col1"]

a    44
b     9
c    70
d    65
Name: Col1, dtype: int64

In [ ]:
df2["Col6"]=df2["Col2"]*df2["Col3"]

In [ ]:
df2

   Col1  Col2  Col3  Col4  Col5  Col6
a    44    47    64    67    67  3008
b     9    83    21    36    87  1743
c    70    88    88    12    58  7744
d    65    39    46    46    88  1794

In [ ]:
df2.iloc[:3,:2]

   Col1  Col2
a    44    47
b     9    83
c    70    88

In [ ]:
df2.loc["a":"c","Col1":"Col4"]

   Col1  Col2  Col3  Col4
a    44    47    64    67
b     9    83    21    36
c    70    88    88    12

In [ ]:
df2[["Col1","Col3","Col4"]]

   Col1  Col3  Col4
a    44    64    67
b     9    21    36
c    70    88    12
d    65    46    46

In [ ]:
df2[df2["Col2"]>50]

   Col1  Col2  Col3  Col4  Col5  Col6
b     9    83    21    36    87  1743
c    70    88    88    12    58  7744

introduction to pandas library

In [ ]:
import pandas as pd

In [ ]:
pd.__version__

'2.1.4'

In [ ]:
# pip install pandas (for installing if not installed)

##Pandas Series

In [ ]:
data=pd.Series([1,2,3,4,5,6])
data

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [ ]:
type(data)

pandas.core.series.Series

In [ ]:
data.values

array([1, 2, 3, 4, 5, 6])

In [ ]:
data.index

RangeIndex(start=0, stop=6, step=1)

In [ ]:
data[1]

2

In [ ]:
data=pd.Series([10,20,30,40,50],index=list("abcde"),
               dtype="float",name="Example Series")
data

a    10.0
b    20.0
c    30.0
d    40.0
e    50.0
Name: Example Series, dtype: float64

In [ ]:
data.vdata=pd.Series([10,20,30,40],index=list("abcd"), # Changed index to "abcd"
               dtype="float",name="Example Series")
data

array([10., 20., 30., 40., 50.])

In [ ]:
data.values

array([10., 20., 30., 40., 50.])

In [ ]:
data.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [ ]:
data.name

'Example Series'

In [ ]:
data.dtype

dtype('float64')

In [ ]:
#dict
pop_dict={"California":123123,
          "Texas":123123,
          "New York":4321,
          "Florida":12353}

In [ ]:
pop_series=pd.Series(pop_dict)
pop_series

California    123123
Texas         123123
New York        4321
Florida        12353
dtype: int64

Dataframe

In [ ]:
area_series={"California":123123,
          "Texas":123123,
          "New York":4321,
          "Florida":12353}

In [ ]:
ser_area=pd.Series(area_series)

In [ ]:
ser_area

California    123123
Texas         123123
New York        4321
Florida        12353
dtype: int64

In [ ]:
df=pd.DataFrame({"population":pop_series,"area":ser_area})
df

            population    area
California      123123  123123
Texas           123123  123123
New York          4321    4321
Florida          12353   12353

In [ ]:
df.columns

Index(['population', 'area'], dtype='object')

In [ ]:
df.index

Index(['California', 'Texas', 'New York', 'Florida'], dtype='object')

In [ ]:
df["area"]

California    123123
Texas         123123
New York        4321
Florida        12353
Name: area, dtype: int64

In [ ]:
df["area"]

California    123123
Texas         123123
New York        4321
Florida        12353
Name: area, dtype: int64

In [ ]:
type(df["area"])

pandas.core.series.Series

In [ ]:
df2=pd.DataFrame(pop_series,columns=["population"])
df2

            population
California      123123
Texas           123123
New York          4321
Florida          12353

In [ ]:
import numpy as np
np.random.seed(0)
arr=np.random.randint(0,100,(4,5))
arr

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88]])

In [ ]:
df2=pd.DataFrame(arr,index=list("abcd"),columns=["col1","col2","col3","col4","col5"])
df2

   col1  col2  col3  col4  col5
a    44    47    64    67    67
b     9    83    21    36    87
c    70    88    88    12    58
d    65    39    87    46    88

In [ ]:
df2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [ ]:
import pandas as pd

In [ ]:
pd.__version__

'2.1.4'

In [ ]:
#pip install pandas

DataFrame

In [ ]:
area_series={"California":123123,
          "Texas":1232323,
          "New York":4451,
          "Florida":123534}

In [ ]:
ser_area=pd.Series(area_series)

In [ ]:
ser_area

California     123123
Texas         1232323
New York         4451
Florida        123534
dtype: int64

In [ ]:
df=pd.DataFrame({"population":pop_series,"area":ser_area})
df

NameError: name 'pop_series' is not defined

In [ ]:
# Create a dictionary named pop_series
pop_series = {"California": 39250017,
              "Texas": 29145505,
              "New York": 19378102,
              "Florida": 21538187}

# Create a Pandas Series from pop_series
ser_pop = pd.Series(pop_series)

# Create a Pandas DataFrame from ser_pop and ser_area
df = pd.DataFrame({"population": ser_pop, "area": ser_area})

# Display the DataFrame
df

            population     area
California    39250017   123123
Texas         29145505  1232323
New York      19378102     4451
Florida       21538187   123534

In [ ]:
df.index

Index(['California', 'Texas', 'New York', 'Florida'], dtype='object')

In [ ]:
df.columns

Index(['population', 'area'], dtype='object')

In [ ]:
df["area"]

California     123123
Texas         1232323
New York         4451
Florida        123534
Name: area, dtype: int64

In [ ]:
type(df["area"])

pandas.core.series.Series

In [ ]:
pd.DataFrame(pop_series,columns=["population"])

In [ ]:
import numpy as np
np.random.seed(0)
arr=np.random.randint(0,100,(4,5))
arr

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88]])

In [ ]:
df2=pd.DataFrame(arr,index=list("abcd"),columns=["col1","col2","col3","col4","col5"])
df

            population     area
California    39250017   123123
Texas         29145505  1232323
New York      19378102     4451
Florida       21538187   123534

In [ ]:
df2.values

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88]])

In [ ]:
df2.index

Index(['a', 'b', 'c', 'd'], dtype='object')